version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
